apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: sd4-frontweb-deployable
  namespace: sd4-chn-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: sd4-application
    subapp: frontweb
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: sd4-frontweb
      namespace: sd4-app-ns
      labels:
        app: sd4-application
        subapp: frontweb
    spec:
      selector:
        matchLabels:
          app: sd4-application
          subapp: frontweb
      replicas: 1
      template:
        metadata:
          labels:
            app: sd4-application
            subapp: frontweb
        spec:
          containers:
          - name: frontweb
            image: "gandhicloudlab/servicediscovery-frontweb:latest"
            imagePullPolicy: Always
            env:
              - name: service.url.catalog
                value: http://sd4-catalog-service.sd4-app-ns.mcm.svc:9090
  dependencies:
  - name: sd4-catalog-service
    namespace: sd4-app-ns
    kind: Service
  placement:
    clusterLabels:
      matchExpressions:
        - key: name
          operator: In
          values:
            - ocp43-mcm-managed-d
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: sd4-frontweb-service-deployable
  namespace: sd4-chn-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: sd4-application
    subapp: frontweb1
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: sd4-frontweb-service
      namespace: sd4-app-ns
      annotations:
        mcm.ibm.com/service-discovery: "{}"
      labels:
        app: sd4-application
        subapp: frontweb
    spec:
      type: LoadBalancer
      ports:
      - port: 9090
        targetPort: 9020
        name: my-http
      selector:
        app: sd4-application
        subapp: frontweb
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: sd4-deployable-route-frontweb
  namespace: sd4-chn-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: sd4-application
    subapp: frontweb1
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: sd4-frontweb
      namespace: sd4-app-ns
      labels:
        app: sd4-application
        subapp: frontweb
    spec:
      path: /
      to:
        kind: Service
        name: sd4-frontweb-service
        weight: 100
      port:
        targetPort: my-http