---
# Source: sd4-subscription/templates/11-application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sd4-application
  namespace: sd4-chn-ns
  labels:
    app: sd4-application
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - sd4-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription